- name: create ec2 and r53 records
  hosts: localhost
  vars:
    aws_region: us-east-1
    instance_type: t2.micro
    image_id: ami-090252cbe067a9e58
    security_group: sg-0e7234dd95db71498
    zone_id: Z08884492QFPW45HM4UQO
    domain: daws78s.online
    instances:
      - name: db
      - name: backend
      - name: frontend
  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      region: "{{ aws_region }}"
      name: "{{ item.name }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ image_id }}"
      security_group: "{{ security_group }}"
    loop: "{{ instances }}"
    register: ec2_info

  - name: Update Route 53 record
    route53:
      state: present
      overwrite: true
      zone: "{{ domain }}"
      record: "{{ item.tags.Name }}.{{ domain }}"
      type: A
      ttl: 3600
      value: "{{ item.public_ip_address if item.tags.Name == 'frontend' else item.private_ip_address }}"
    loop: "{{ ec2_info.instances }}"