- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: Install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: start nginx server
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  
  - name: remove default site
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

  - name: create directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory